RingbitCar.init_wheel(AnalogPin.P1, AnalogPin.P2)
basic.forever(function () {
    RingbitCar.freestyle(55, 42)
    basic.pause(4000)
    RingbitCar.brake()
    basic.pause(1000)
    RingbitCar.steering_angle(RingbitCar.Direction_turn.right, 100)
    basic.pause(2000)
    RingbitCar.brake()
    basic.pause(1000)
    RingbitCar.freestyle(55, 42)
    basic.pause(4000)
    RingbitCar.brake()
    basic.pause(1000)
    RingbitCar.steering_angle(RingbitCar.Direction_turn.left, 100)
    basic.pause(2000)
    RingbitCar.brake()
    basic.pause(1000)
})
